release-date = "2020-08-29"

[[entries]]
id = "27920260-c47e-4191-9f3a-5249584d28a3"
type = "improvement"
description = "ensure that non-default arguments do not have a class attribute of type `object` (which is used as a workaround to support non-default fields following default fields in `dataclasses`)"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "0d15905e-4810-4c08-a4d8-70aaa72ad4f0"
type = "fix"
description = "raise for uninitialized fields inherited from parent datamodels"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "71c62ec7-7d37-4461-96a3-217de03499de"
type = "improvement"
description = "`ArrayConverter` now supports subclasses of the `typing.List` generic"
author = "@NiklasRosenstein"
component = "databind.json"
