release-date = "2020-09-10"

[[entries]]
id = "da1141be-ec57-4d28-a50a-1158dca6107b"
type = "fix"
description = "`Registry.get_converter()` now looks for a converter in the base classes only if it could not find it for the normalized version of the current type, making converter resolution more predictable"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "df476ea6-934c-440c-92be-d41f4bc8422c"
type = "feature"
description = "Add `ClassUnionResolver` which evaluates type hints dynamically, allowing to use forward references in the type hints of a `@uniontype()`"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "65bd22be-4505-4b45-ad8a-b0f7f6307312"
type = "feature"
description = "Add `@interface()` and `@implementation()` decorators"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "cc7ad2d7-1ba6-428a-8f49-b7407ccdc505"
type = "feature"
description = "Add `to_stream()` and `from_stream()` functions"
author = "@NiklasRosenstein"
component = "databind.json"

[[entries]]
id = "bc0a165d-7868-415c-9b52-8f9ad9040cb9"
type = "feature"
description = "Add support for `typing.Dict` subclasses"
author = "@NiklasRosenstein"
component = "databind.json"
