release-date = "2021-08-20"

[[entries]]
id = "2bfa9bb8-736b-4f42-ae79-662ac60d6c95"
type = "feature"
description = "add `Direction.is_serialize()` and `Direction.is_deserialize()`"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "9ca8468e-f716-4033-a07d-7c06d3d3e549"
type = "feature"
description = "add `AnnotationsRegistry.add_type_annotation()` and `AnnotationsRegistry.add_field_annotation()`"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "e8fa6c70-9732-40a3-a7d8-54d772e21ba9"
type = "feature"
description = "`DefaultAnnotationsProvider` now supports finding annotations in `Enum` members when annotated with `te.Annotated`, `DefaultAnnotationsProvider` is now registered to an `ObjectMapper` by default"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "c09f08bb-ce01-49f8-b3bc-94fb8d27a2e5"
type = "feature"
description = "add converter for `pathlib.PurePath` subclasses, enabled in the `JsonModule` by default"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/databind/issues/14",
]
component = "databind.json"

[[entries]]
id = "6b4a28ad-478a-4ae8-bfb8-58e3730bfee5"
type = "feature"
description = "add converter for `uuid.UUID` to `JsonModule`"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/databind/issues/15",
]
component = "databind.json"

[[entries]]
id = "c067911a-cee5-416a-b05d-19801bccbb27"
type = "feature"
description = "support aliases on enum values"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/databind/issues/1",
]
component = "databind.json"
