release-date = "2022-01-08"

[[entries]]
id = "18a0d099-5539-451e-94ef-52e9453ca20a"
type = "fix"
description = "Dataclass adapted to ObjectType with no schema fields if a field cannot be adapted"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/databind/issues/23",
]
component = "databind.core"

[[entries]]
id = "aefb76ba-5f30-4589-a5bd-e482851e9351"
type = "feature"
description = "support resolving forward references in PEP585 generic aliases"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/databind/issues/24",
]
component = "databind.core"

[[entries]]
id = "cc443d45-6490-4291-890f-ef6ed1555c90"
type = "improvement"
description = "change `ConverterProvider.get_converter()` to `ConverterProvider.get_converters()` and `ConversionNotApplicable` error type, allowing to test multiple converters for a type"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "d192ebd0-f643-4823-bbbe-ec20b878d8b2"
type = "feature"
description = "add `databind.json.annotations.with_custom_json_converter()` annotation to allow implementing a custom converter for dataclasses"
author = "@NiklasRosenstein"
component = "databind.json"

[[entries]]
id = "f5a426e0-21c1-415f-b7b3-c975d357f5a4"
type = "fix"
description = "narrow `JsonType` union type to use `dict` and `list` instead of `t.Mapping` and `t.Collection`"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/databind/issues/22",
]
component = "databind.json"
