release-date = "2022-05-11"

[[entries]]
id = "bc8211d9-3762-44cb-8de8-bb0f7b56726a"
type = "fix"
description = "Fixed an issue where the frame for a dataclass type saved with `typeapi.scoped` was not respected for type evaluation."
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "1c10d176-2231-4632-a67b-458d71bdd523"
type = "fix"
description = "Fixed module-scoped evaluation of forward references for subclasses of `typing.TypedDict`."
author = "@NiklasRosenstein"
component = "databind.core"
