release-date = "2022-03-29"

[[entries]]
id = "3bac26ba-57d6-4953-8393-386c618e1d14"
type = "fix"
description = "Fix error in `ConversionError.expected()` if the `types` parameter was a type hint"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "9439eaa0-19ba-4b9e-9437-b59c55219550"
type = "breaking change"
description = "add `ConversionError()` `origin` and `errors` parameter"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "9f5996fe-a2bf-4fb5-b8bf-42c526673d93"
type = "breaking change"
description = "implement `Union.BEST_MATCH` in `UnionConverter`, which is now used as the default if an un-annotated `typing.Union` is encountered"
author = "@NiklasRosenstein"
component = "databind.json"
