release-date = "2022-05-09"

[[entries]]
id = "77ea4dca-ae09-4454-9c01-2687ff3d57ad"
type = "improvement"
description = "Loosen requirement on `typing-extensions` from `^3.10.0` to `>=3.10.0`"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "adf0e51f-ba27-4421-a5a4-f771b5e5221e"
type = "refactor"
description = "Use Black and isort for code formatting, Flake8 for linting"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "e13ad790-4e0a-44fb-afec-3ecc7c6b9ad8"
type = "improvement"
description = "Loosen requirement on `typing-extensions` from `^3.10.0` to `>=3.10.0`"
author = "@NiklasRosenstein"
component = "databind.json"

[[entries]]
id = "b537c6b7-fa06-41b4-a452-8edb5b0f6fe4"
type = "refactor"
description = "Use Black and isort for code formatting, Flake8 for linting"
author = "@NiklasRosenstein"
component = "databind.json"
