release-date = "2022-06-20"

[[entries]]
id = "56621ccd-8ec3-409a-84f6-9ec4ce1a052f"
type = "improvement"
description = "Enable Mypy strict type checking mode"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "df546027-bed8-46e1-8e9d-caa6447142bf"
type = "improvement"
description = "Enable Mypy strict type checking mode"
author = "@NiklasRosenstein"
component = "databind.json"
