release-date = "2022-05-11"

[[entries]]
id = "f15a4a8f-c74e-4e71-801a-0f5ee411d227"
type = "docs"
description = "Add URLs to project metadata."
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "690814ed-1018-4a1d-b67f-4c1152003ce0"
type = "improvement"
description = "Schemas (dataclasses, typed dicts) that have an `Optional` field that are not explicitly marked as `Required()` now automatically get assigned `None` as a default value"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "2b9885cd-5196-45dd-8b3e-3b8d10d8f708"
type = "docs"
description = "Add URLs to project metadata."
author = "@NiklasRosenstein"
component = "databind.json"

[[entries]]
id = "a37639a0-d0bd-40e1-8b8b-06dbd6b96d9e"
type = "improvement"
description = "Use a fields default value if it is available when deserializing schemas"
author = "@NiklasRosenstein"
component = "databind.json"
