release-date = "2022-11-10"

[[entries]]
id = "f368b4b8-414a-4791-a01b-2012c5dc99b6"
type = "tests"
description = "add a unnit test to see if the conversion of nested dataclasses with forward references works as expected (breaks in Python 3.6.2)"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "9f76e90c-650f-4725-bfd2-fe566f62406c"
type = "fix"
description = "Set min version to 3.6.3 because of a `typing.get_type_hints()` incompatibiltiy"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "df9af6b0-896e-41f5-846f-550de25c2db9"
type = "fix"
description = "Set min version to 3.6.3 because of a `typing.get_type_hints()` incompatibiltiy"
author = "@NiklasRosenstein"
component = "databind.json"

[[entries]]
id = "ed7e9626-ccad-469f-acaa-b3e6225cf6d9"
type = "feature"
description = "support deserialization of tuples"
author = "@NiklasRosenstein"
component = "databind.json"
