release-date = "2023-05-28"

[[entries]]
id = "f6034daf-a9d7-46d5-8430-4128b89c05e9"
type = "tests"
description = "Type-check unit tests"
author = "@NiklasRosenstein"
component = "databind"

[[entries]]
id = "34f4cbf8-4bd4-4b6d-837f-6bf4b2006803"
type = "feature"
description = "Add `DeserializeAs` setting"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "78606f4e-7b4c-4f88-9143-e40b12d86100"
type = "improvement"
description = "Expose public API in `databind.core` root module."
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "8d5cd812-ba8f-4c4d-9681-b0d8866ae023"
type = "improvement"
description = "Mark some more settings as frozen or add unsafe hash functions to support passing them as metadata to `typing_extensions.Annotated` in Python 3.6"
author = "@NiklasRosenstein"
component = "databind.core"

[[entries]]
id = "5d31c345-35ef-40f4-bf02-bfca907f0517"
type = "feature"
description = "Support new `DeserializeAs` setting"
author = "@NiklasRosenstein"
component = "databind.json"

[[entries]]
id = "e8a41ce4-27c1-4706-a154-fb2488c342dd"
type = "improvement"
description = "Expose public API in `databind.json` root module."
author = "@NiklasRosenstein"
component = "databind.json"

[[entries]]
id = "5bbbae6a-fb76-4657-b16d-27358ae9f22d"
type = "tests"
description = "Type-check unit tests"
author = "@NiklasRosenstein"
component = "databind.json"
