release-date = "2023-06-09"

[[entries]]
id = "eee787ce-d9d3-442e-acee-b274edc72176"
type = "fix"
description = "Evaluate forward references when creating schema for NamedTuples"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/python-databind/pull/50"
component = "databind.json"
