release-date = "2023-06-21"

[[entries]]
id = "b44947f0-8e70-4a29-b584-a20eeff51bba"
type = "fix"
description = "Fixed serde of types that have a parameterized generic base class. (First reported in NiklasRosenstein/pydoc-markdown#292)"
author = "rosensteinniklas@gmail.com"
pr = "https://github.com/NiklasRosenstein/python-databind/pull/51"
component = "databind.core"

[[entries]]
id = "43fe920b-b6b9-4701-9403-bff9aba2e744"
type = "improvement"
description = "Work around highly nested error tracebacks in `Module.convert()` by expanding all converters returned by `Module.get_converter()`. Note that this means `Module.convert()` is no longer called if the module is a child of another module."
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/python-databind/pull/52"
component = "databind.core"

[[entries]]
id = "e2e3fbdf-b19c-443d-bc79-8560dba4b1b5"
type = "improvement"
description = "Add `DelegateToClassmethodConverter(serialized_type)` parameter."
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/python-databind/pull/52"
component = "databind.core"

[[entries]]
id = "6ac5f7d0-aeb8-436c-bc2c-a178e2a82a74"
type = "tests"
description = "Add a unit tests to demonstrate that deserializing a nested type cannot work."
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/python-databind/pull/51"
component = "databind.json"

[[entries]]
id = "89204ef2-6173-4d4e-b857-3af59db2de32"
type = "fix"
description = "Technically a breaking change, but any consumer who is relying on this behaviour probably does that implicitly and wants to change their code anyway. o_o -- The `CollectionConverter` no longer implicitly assumes `Any` as the item type if collection is not parameterized."
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/python-databind/pull/52"
component = "databind.json"

[[entries]]
id = "0b05e104-7012-4a03-a995-12ed05878f0b"
type = "improvement"
description = "The `CollectionConverter` now properly infers the item type from the types base classes"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/python-databind/pull/52"
component = "databind.json"

[[entries]]
id = "ae147797-2857-4e6e-b7af-d2c6c1152e59"
type = "improvement"
description = "The `MappingConverter` now does improved resolution of the key and value type just like the `CollectionConverter`; note that an unparameterized Mapping no longer has its key and value type fall back to `typing.Any`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/python-databind/pull/52"
component = "databind.json"

[[entries]]
id = "08e63490-84b9-418d-8f26-39c770f17d59"
type = "improvement"
description = "Use `ConversionError.expected()` factory function in `PlainDatatypeConverter`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/python-databind/pull/52"
component = "databind.json"

[[entries]]
id = "78c6beda-22dd-419e-848f-5835ab554efd"
type = "tests"
description = "Test `JsonConverter`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/python-databind/pull/52"
component = "databind.json"
