[changelog]
enabled = false

[run]
"docs:build" = "cd docs && novella --base-url python-databind/"
"docs:dev" = "cd docs && novella --serve"

[test]
check = "slap check"

[install.extras]
docs = ['pydoc-markdown==4.6.0', 'novella==0.2.3', 'mkdocs', 'mkdocs-material']
