name: databind
version: 1.0.0
description: |
  Databind is a library inspired by jackson-databind to de-/serialize Python dataclasses. The `databind` package
  will install the full suite of databind packages. Compatible with Python 3.6 and newer.
readme: ../README.md
requirements:
- python ^3.6
- databind.core ^1.0.0
- databind.json ^1.0.0
