name: databind.tagline
version: 0.1.3
description: De/serialize strings of comma-separated key-value pairs using Python
  type hints.
typed: true
requirements:
- python ^3.5
- databind.core ^0.4.0
- databind.json ^0.5.0
- nr.parsing.core ~1.0.0
test-driver:
  type: pytest
