name: "databind.json"
version: "0.1.0"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "Bind object-oriented data models to JSON data."
requirements:
- python ^3.7
- databind.core ^0.1.0
- nr.parsing.date ^0.3.0
