name: databind.json
version: 1.1.5
description: |
  De-/serialize Python dataclasses to or from JSON payloads. Compatible with Python 3.7 and newer.
typed: true
requirements:
- databind.core ^1.1.5
- python ^3.7
- typing_extensions ^3.10.0
- nr.parsing.date ^1.0.1
- nr.preconditions ^0.0.4
dev-requirements:
- mypy
test-drivers:
  - type: pytest
  - type: mypy
