name: databind.json
version: 1.3.0
description: |
  De-/serialize Python dataclasses to or from JSON payloads. Compatible with Python 3.7 and newer.
typed: true
requirements:
- databind.core ^1.3.0
- python ^3.7
- typing_extensions ^3.10.0
- nr.optional ^0.1.1
- nr.parsing.date ^1.0.1
- nr.preconditions ^0.0.4
test-drivers:
- type: pytest
- type: mypy
