[build-system]
requires = ["uv_build>=0.11.1,<0.12"]
build-backend = "uv_build"

[project]
name = "databind.json"
version = "4.5.4"
description = "De-/serialize Python dataclasses to or from JSON payloads. Compatible with Python 3.8 and newer. Deprecated, use `databind` module instead."
authors = [{name = "Niklas Rosenstein", email = "rosensteinniklas@gmail.com"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "databind>=4.5.4,<5",
]

[project.urls]
"Bug Tracker" = "https://github.com/NiklasRosenstein/python-databind/issues"
Documentation = "https://niklasrosenstein.github.io/python-databind/"
Repository = "https://github.com/NiklasRosenstein/python-databind"

[tool.uv.sources]
databind = { workspace = true }

[tool.uv.build-backend]
module-name = "_databind_json_proxy"
