name: databind.binary
version: 0.2.1
description: Bind object-oriented data models to binary data encoded with the struct
  module.
typed: true
requirements:
- python ^3.6
- databind.core ^0.1.0
test-driver:
  type: pytest
