release-date = "2020-08-29"

[[entries]]
id = "d54aa0ac-9329-4d2a-8e3a-16063491f764"
type = "improvement"
description = "update type hints to pass mypy checks"
author = "@NiklasRosenstein"

[[entries]]
id = "47206f43-6699-40ea-8210-c1a341d2b623"
type = "improvement"
description = "`FieldMetadata` now keeps a reference to the `dataclasses.Field` object and it's' metadata"
author = "@NiklasRosenstein"
