release-date = "2020-11-20"

[[entries]]
id = "bc008cf1-db00-4789-9362-7b5c47af1d26"
type = "fix"
description = "Python 3.9 support in type hint normalization"
author = "@NiklasRosenstein"

[[entries]]
id = "8465d65a-3f95-4a9f-aa18-e8810999b5ec"
type = "fix"
description = "fix mypy errors"
author = "@NiklasRosenstein"
