release-date = "2021-07-23"

[[entries]]
id = "047bcdde-be03-419a-b2ff-351c1519e69b"
type = "improvement"
description = "import `dataclass_to_schema` into `databind.core` top-level package"
author = "@NiklasRosenstein"

[[entries]]
id = "cd9d09c1-7801-4125-8274-4745295c584a"
type = "fix"
description = "fix type hints to pass mypy checks"
author = "@NiklasRosenstein"
