release-date = "2021-08-16"

[[entries]]
id = "efbf0a33-5eae-4868-84e0-00d252c7a08d"
type = "fix"
description = "normal type with `Annotated[MyType, union(...)]` is now correctly interpreted as `UnionType`"
author = "@NiklasRosenstein"
