release-date = "2021-08-20"

[[entries]]
id = "2bfa9bb8-736b-4f42-ae79-662ac60d6c95"
type = "feature"
description = "add `Direction.is_serialize()` and `Direction.is_deserialize()`"
author = "@NiklasRosenstein"

[[entries]]
id = "9ca8468e-f716-4033-a07d-7c06d3d3e549"
type = "feature"
description = "add `AnnotationsRegistry.add_type_annotation()` and `AnnotationsRegistry.add_field_annotation()`"
author = "@NiklasRosenstein"

[[entries]]
id = "e8fa6c70-9732-40a3-a7d8-54d772e21ba9"
type = "feature"
description = "`DefaultAnnotationsProvider` now supports finding annotations in `Enum` members when annotated with `te.Annotated`, `DefaultAnnotationsProvider` is now registered to an `ObjectMapper` by default"
author = "@NiklasRosenstein"
