release-date = "2022-05-11"

[[entries]]
id = "f15a4a8f-c74e-4e71-801a-0f5ee411d227"
type = "docs"
description = "Add URLs to project metadata."
author = "@NiklasRosenstein"

[[entries]]
id = "690814ed-1018-4a1d-b67f-4c1152003ce0"
type = "improvement"
description = "Schemas (dataclasses, typed dicts) that have an `Optional` field that are not explicitly marked as `Required()` now automatically get assigned `None` as a default value"
author = "@NiklasRosenstein"
