release-date = "2022-03-24"

[[entries]]
id = "321e07d2-6720-4a85-acb0-6975779a0cdf"
type = "improvement"
description = "move `ExtraKeys` and `Remainder` setting from `databind.json` to `databind.core`"
author = "@NiklasRosenstein"

[[entries]]
id = "20fd7449-70e4-4200-8058-f03e20155485"
type = "feature"
description = "make `ExtraKeys` setting a subclass of `ClassDecoratorSetting`, allowing it to be used to mark an entire class and allowing extra keys"
author = "@NiklasRosenstein"
