release-date = "2022-11-21"

[[entries]]
id = "33063789-c83a-4d0d-967c-9093984dbc62"
type = "improvement"
description = "improve error message display format and add a default implementation for `Converter.__repr__()`"
author = "@NiklasRosenstein"

[[entries]]
id = "ea24af2b-0378-414e-8452-d8b379e8b780"
type = "improvement"
description = "when a `ConversionError` occurs, we continue with the remaining converters to attempt to convert it until we are all out of options"
author = "@NiklasRosenstein"
