release-date = "2023-05-28"

[[entries]]
id = "34f4cbf8-4bd4-4b6d-837f-6bf4b2006803"
type = "feature"
description = "Add `DeserializeAs` setting"
author = "@NiklasRosenstein"

[[entries]]
id = "78606f4e-7b4c-4f88-9143-e40b12d86100"
type = "improvement"
description = "Expose public API in `databind.core` root module."
author = "@NiklasRosenstein"

[[entries]]
id = "8d5cd812-ba8f-4c4d-9681-b0d8866ae023"
type = "improvement"
description = "Mark some more settings as frozen or add unsafe hash functions to support passing them as metadata to `typing_extensions.Annotated` in Python 3.6"
author = "@NiklasRosenstein"
