[[entries]]
id = "b44947f0-8e70-4a29-b584-a20eeff51bba"
type = "fix"
description = "Fixed serde of types that have a parameterized generic base class. (First reported in NiklasRosenstein/pydoc-markdown#292)"
author = "rosensteinniklas@gmail.com"
