[[entries]]
id = "a2b1ca0b-832c-4bae-8e7d-d99598dfacbd"
type = "fix"
description = "fix type hint for `ClassDecoratorSetting.__call__()` which would confuse Pylance"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/python-databind/issues/34"
