[[entries]]
id = "1c19df94-6996-466e-a0b4-7e8b2111fe6a"
type = "feature"
description = "add `DelegateToClassmethodConverter` class"
author = "@NiklasRosenstein"

[[entries]]
id = "ce944eb9-871d-498a-9f23-5f54bf3d589e"
type = "feature"
description = "add `JsonConverter.using_classmethods()` method"
author = "@NiklasRosenstein"
