[[entries]]
id = "bc8211d9-3762-44cb-8de8-bb0f7b56726a"
type = "fix"
description = "Fixed an issue where the frame for a dataclass type saved with `typeapi.scoped` was not respected for type evaluation."
author = "@NiklasRosenstein"
