[[entries]]
id = "321e07d2-6720-4a85-acb0-6975779a0cdf"
type = "improvement"
description = "move `ExtraKeys` and `Remainder` setting from `databind.json` to `databind.core`"
author = "@NiklasRosenstein"
