name: databind.core
version: 0.11.0
description: Databind is a library inspired by Jackson-databind to describe and bind
  data models for object-oriented programming.
typed: true
requirements:
- python ^3.6
- dataclasses ^0.6
- nr.optional ^0.1.0
- nr.preconditions ^0.0.2
- nr.pylang.utils ^0.1.1
- nr.stream ^0.1.1
test-driver:
  type: pytest
