name: databind.core
version: 0.11.0
description: Databind is a library inspired by Jackson-databind to describe and bind
  data models for object-oriented programming.
typed: true
requirements:
- python ^3.6
- dataclasses ^0.6
- nr.preconditions ^0.0.2
test-driver:
  type: pytest
