name: databind.core
version: 1.2.6
description: |
  Databind is a library inspired by jackson-databind to de-/serialize Python dataclasses.
  Compatible with Python 3.7 and newer.
typed: true
requirements:
- python ^3.7
- typing_extensions ^3.10.0
- nr.optional ^0.1.1
- nr.parsing.date ^1.0.1
- nr.preconditions ^0.0.4
- nr.pylang.utils ^0.1.3
- nr.stream ^0.1.1
- Deprecated ^1.2.12
test-requirements:
- types-dataclasses
- types-deprecated
- types-pkg_resources
test-drivers:
- type: pytest
- type: mypy
