release-date = "2020-08-29"

[[entries]]
id = "3195561b-c5ed-4595-922b-9d76c46892f9"
type = "improvement"
description = "update type hints to pass mypy checks"
author = "@NiklasRosenstein"

[[entries]]
id = "c3458aff-e6b3-4b20-97b0-12882818b6db"
type = "improvement"
description = "add DEBUG log when `MixtypeConverter` is unable to convert a value at all to make debugging easier"
author = "@NiklasRosenstein"

[[entries]]
id = "37e0f485-54c0-4bcf-bd3e-082f629b8689"
type = "fix"
description = "accept `datetime.date`/`datetime.datetime` objects when converting to python if the target type is a respective match (rather than forcing a string as an input)"
author = "@NiklasRosenstein"
