release-date = "2020-08-29"

[[entries]]
id = "71c62ec7-7d37-4461-96a3-217de03499de"
type = "improvement"
description = "`ArrayConverter` now supports subclasses of the `typing.List` generic"
author = "@NiklasRosenstein"
