release-date = "2022-01-22"

[[entries]]
id = "af09d38c-66ee-4399-a9a7-404a1911add5"
type = "feature"
description = "support `union.Style.keyed`"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/databind/issues/21",
]
