release-date = "2022-11-03"

[[entries]]
id = "6ae51d42-f0e1-4d1a-85bc-0bf5c4ec7623"
type = "feature"
description = "add `JsonConverter()` setting to override the converter used for JSON de-/serialization"
author = "@NiklasRosenstein"
