[[entries]]
id = "fde3ca08-6897-4a16-a4d9-b794da8dd702"
type = "fix"
description = "Fixed an issue when deserializing fields in a schema when the Python type does not have the exact same representation in the structured payload, causing an error when that Python default value is handed as a value to be deserialized."
author = "@NiklasRosenstein"
