[[entries]]
id = "f80f15cd-54ce-465e-a9b7-e88040ad380e"
type = "tests"
description = "add unit tests for deserializing `duration` from an object form"
author = "@NiklasRosenstein"

[[entries]]
id = "32461220-a197-4d09-aa81-d9c8c827a637"
type = "docs"
description = "update readme to list supported types"
author = "@NiklasRosenstein"
