[[entries]]
id = "7478f5e3-d2cc-43f0-a557-753c8420ed4b"
type = "breaking change"
description = "Databind is now compatible with Python 3.6! This required a few breaking changes to the API used to extend Databind, which is why this is a major version bump. We now use `typeapi 1.x` which has a significantly different API but enables the Python 3.6 compatibilty."
author = "@NiklasRosenstein"
