[[entries]]
id = "8bfab3e3-e014-4e99-a647-5af5e47aa6c7"
type = "improvement"
description = "add `StringifyConverter(name)` parameter and improve `__repr__()`"
author = "@NiklasRosenstein"

[[entries]]
id = "e44aff02-4fe8-48d6-b26a-6e41f0ca53ea"
type = "fix"
description = "fix order of converters for `pathlib.Path` and `pathlib.PurePath` registered to the `JsonModule`"
author = "@NiklasRosenstein"
