[[entries]]
id = "6ac5f7d0-aeb8-436c-bc2c-a178e2a82a74"
type = "tests"
description = "Add a unit tests to demonstrate that deserializing a nested type cannot work."
author = "@NiklasRosenstein"

[[entries]]
id = "89204ef2-6173-4d4e-b857-3af59db2de32"
type = "fix"
description = "Technically a breaking change, but any consumer who is relying on this behaviour probably does that implicitly and wants to change their code anyway. o_o -- The `CollectionConverter` no longer implicitly assumes `Any` as the item type if collection is not parameterized."
author = "@NiklasRosenstein"

[[entries]]
id = "0b05e104-7012-4a03-a995-12ed05878f0b"
type = "improvement"
description = "The `CollectionConverter` now properly infers the item type from the types base classes"
author = "@NiklasRosenstein"

[[entries]]
id = "ae147797-2857-4e6e-b7af-d2c6c1152e59"
type = "improvement"
description = "The `MappingConverter` now does improved resolution of the key and value type just like the `CollectionConverter`; note that an unparameterized Mapping no longer has its key and value type fall back to `typing.Any`"
author = "@NiklasRosenstein"
