nav:
  - Home:
    - index.md
    - changelog.md
  - databind.core:
    - core/index.md
    - core/basic-usage.md
    - core/settings.md
    - core/dataclass-ext.md
    - API: []
  - databind.json:
    - json/index.md
    - Examples:
      - json/examples/index.md
      - json/examples/config-serde.md
      - json/examples/unions.md
      - json/examples/unknown-keys.md
    - API: []
