nav:
  - Home: index.md
  - CORE:
    - core/index.md
    - core/basic-usage.md
    - core/settings.md
    - core/dataclass-ext.md
    - core/changelog.md
    - API: []
  - JSON:
    - json/index.md
    - Examples:
      - json/examples/index.md
      - json/examples/config-serde.md
      - json/examples/unions.md
      - json/examples/unknown-keys.md
    - json/changelog.md
    - API: []
