nav:
  - Home: index.md
  - databind.core.md
  - databind.json.md
  - examples.md
  - API: []  # Updated by build.novella
  - Changelogs:
    - changelog/databind.core.md
    - changelog/databind.json.md
